const dicionario = [
  { fr: "à", pt: "em, para", type: "prép." },
  { fr: "accepter", pt: "aceitar", type: "v.", isVerb: true },
  { fr: "adorer", pt: "adorar", type: "v.", isVerb: true },
  { fr: "adulte", pt: "adulto", type: "n.m." },
  { fr: "ajouter", pt: "acrescentar", type: "v.", isVerb: true },
  { fr: "aimer", pt: "amar, gostar (de)", type: "v.", isVerb: true },
  { fr: "ami", pt: "amigo", type: "n.m." },
  { fr: "ananas", pt: "abacaxi", type: "n.m." },
  { fr: "après", pt: "depois", type: "prép./adv." },
  { fr: "arriver", pt: "chegar", type: "v.", isVerb: true },
  { fr: "assis, assise", pt: "sentado, -a", type: "adj." },
  { fr: "attraper", pt: "pegar, agarrar", type: "v.", isVerb: true },
  { fr: "au marché", pt: "no mercado", type: "loc." },
  { fr: "aujourd'hui", pt: "hoje", type: "adv." },
  { fr: "aussi", pt: "também", type: "adv." },
  { fr: "avec", pt: "com", type: "prép." },
  { fr: "banane", pt: "banana", type: "n.f." },
  { fr: "beau, belle", pt: "bonito, -a", type: "adj." },
  { fr: "beaucoup", pt: "muito", type: "adv." },
  { fr: "bibliothèque", pt: "biblioteca", type: "n.f." },
  { fr: "biscuit", pt: "biscoito", type: "n.m." },
  { fr: "boire", pt: "beber", type: "v.", isVerb: true },
  { fr: "bon, bonne", pt: "bom, boa", type: "adj." },
  { fr: "bras", pt: "braço", type: "n.m." },
  { fr: "briller", pt: "brilhar", type: "v.", isVerb: true },
  { fr: "café", pt: "café", type: "n.m." },
  { fr: "cahier", pt: "caderno", type: "n.m." },
  { fr: "cantine", pt: "cantina", type: "n.f." },
  { fr: "chaud, chaude", pt: "quente", type: "adj." },
  { fr: "chemin", pt: "caminho", type: "n.m." },
  { fr: "chez", pt: "na casa de", type: "prép." },
  { fr: "chocolat chaud", pt: "chocolate quente", type: "n.m." },
  { fr: "classe", pt: "classe, turma", type: "n.f." },
  { fr: "commencer", pt: "começar", type: "v.", isVerb: true },
  { fr: "cour", pt: "pátio", type: "n.f." },
  { fr: "courir", pt: "correr", type: "v.", isVerb: true },
  { fr: "cousin", pt: "primo", type: "n.m." },
  { fr: "crayon de couleur", pt: "lápis de cor", type: "n.m." },
  { fr: "cuisine", pt: "cozinha", type: "n.f." },
  { fr: "cuit, cuite", pt: "cozido, -a", type: "adj." },
  { fr: "dans", pt: "em, dentro de", type: "prép." },
  { fr: "déjà", pt: "já", type: "adv." },
  { fr: "demander", pt: "perguntar", type: "v.", isVerb: true },
  { fr: "dessert", pt: "sobremesa", type: "n.m." },
  { fr: "dîner", pt: "jantar", type: "n.m." },
  { fr: "dire", pt: "dizer", type: "v.", isVerb: true },
  { fr: "découper", pt: "fatiar, recortar", type: "v.", isVerb: true },
  { fr: "école", pt: "escola", type: "n.f." },
  { fr: "écrire", pt: "escrever", type: "v.", isVerb: true },
  { fr: "enfant", pt: "criança", type: "n.m./f." },
  { fr: "enfin", pt: "enfim, finalmente", type: "adv." },
  { fr: "ensemble", pt: "juntos", type: "adv." },
  { fr: "enseignante", pt: "professora", type: "n.f." },
  { fr: "être", pt: "ser, estar", type: "v.", isVerb: true },
  { fr: "exercice", pt: "exercício", type: "n.m." },
  { fr: "famille", pt: "família", type: "n.f." },
  { fr: "farine de blé", pt: "farinha de trigo", type: "n.f." },
  { fr: "fatigué, fatiguée", pt: "cansado, -a", type: "adj." },
  { fr: "finir", pt: "terminar, acabar", type: "v.", isVerb: true },
  { fr: "fleur", pt: "flor", type: "n.f." },
  { fr: "frais, fraîche", pt: "fresco, -a", type: "adj." },
  { fr: "fromage", pt: "queijo", type: "n.m." },
  { fr: "gâteau", pt: "bolo", type: "n.m." },
  { fr: "glace", pt: "sorvete", type: "n.f." },
  { fr: "goûter", pt: "provar, o lanche", type: "v.", isVerb: true },
  { fr: "grand-mère", pt: "avó", type: "n.f." },
  { fr: "grand-père", pt: "avô", type: "n.m." },
  { fr: "gymnase", pt: "ginásio, quadra", type: "n.m." },
  { fr: "habiter", pt: "morar", type: "v.", isVerb: true },
  { fr: "haricot", pt: "feijão", type: "n.m." },
  { fr: "heureux, heureuse", pt: "feliz", type: "adj." },
  { fr: "huile", pt: "óleo", type: "n.f." },
  { fr: "il fait chaud", pt: "está calor, faz calor", type: "loc." },
  { fr: "il y a", pt: "há, existe, tem", type: "loc. verbale" },
  { fr: "jambe", pt: "perna", type: "n.f." },
  { fr: "jardin", pt: "jardim", type: "n.m." },
  { fr: "jaune", pt: "amarelo, -a", type: "adj." },
  { fr: "joie", pt: "alegria", type: "n.f." },
  { fr: "jouer", pt: "brincar, jogar", type: "v.", isVerb: true },
  { fr: "jus d'orange", pt: "suco de laranja", type: "n.m." },
  { fr: "jusqu'à", pt: "até", type: "prép." },
  { fr: "lait", pt: "leite", type: "n.m." },
  { fr: "se laver les mains", pt: "lavar as mãos", type: "loc. verbale", isVerb: true },
  { fr: "légume", pt: "legume, vegetal", type: "n.m." },
  { fr: "leur", pt: "seu, sua (deles/delas)", type: "adj. poss." },
  { fr: "lever la main", pt: "levantar a mão", type: "loc. verbale", isVerb: true },
  { fr: "madame", pt: "senhora", type: "n.f." },
  { fr: "main", pt: "mão", type: "n.f." },
  { fr: "maison", pt: "casa", type: "n.f." },
  { fr: "mangue", pt: "manga", type: "n.f." },
  { fr: "manger", pt: "comer", type: "v.", isVerb: true },
  { fr: "marché", pt: "mercado", type: "n.m." },
  { fr: "marcher", pt: "andar, caminhar", type: "v.", isVerb: true },
  { fr: "matin", pt: "manhã", type: "n.m." },
  { fr: "mélanger", pt: "misturar", type: "v.", isVerb: true },
  { fr: "mer", pt: "mar", type: "n.f." },
  { fr: "merci", pt: "obrigado, -a", type: "interj." },
  { fr: "mère", pt: "mãe", type: "n.f." },
  { fr: "mettre la table", pt: "pôr a mesa", type: "loc. verbale", isVerb: true },
  { fr: "midi", pt: "meio-dia", type: "n.m." },
  { fr: "moment", pt: "momento", type: "n.m." },
  { fr: "œuf", pt: "ovo", type: "n.m." },
  { fr: "oncle", pt: "tio", type: "n.m." },
  { fr: "oui", pt: "sim", type: "adv./interj." },
  { fr: "ouvrir", pt: "abrir", type: "v.", isVerb: true },
  { fr: "pain", pt: "pão", type: "n.m." },
  { fr: "pain de mie", pt: "pão de forma", type: "n.m." },
  { fr: "parce que", pt: "porque", type: "loc. conj." },
  { fr: "parler", pt: "falar", type: "v.", isVerb: true },
  { fr: "pâtes", pt: "massas, macarrão", type: "n.f. pl." },
  { fr: "pendant que", pt: "enquanto", type: "loc. conj." },
  { fr: "petit-déjeuner", pt: "café da manhã", type: "n.m." },
  { fr: "un peu de", pt: "um pouco de", type: "loc." },
  { fr: "plage", pt: "praia", type: "n.f." },
  { fr: "poulet", pt: "frango", type: "n.m." },
  { fr: "préparer", pt: "preparar", type: "v.", isVerb: true },
  { fr: "près de", pt: "perto de", type: "loc. prép." },
  { fr: "prendre", pt: "pegar, tomar", type: "v.", isVerb: true },
  { fr: "ranger", pt: "guardar, arrumar", type: "v.", isVerb: true },
  { fr: "récréation", pt: "recreio", type: "n.f." },
  { fr: "regarder", pt: "olhar, assistir", type: "v.", isVerb: true },
  { fr: "règle", pt: "régua", type: "n.f." },
  { fr: "répondre", pt: "responder", type: "v.", isVerb: true },
  { fr: "riz", pt: "arroz", type: "n.m." },
  { fr: "sandwich", pt: "sanduíche", type: "n.m." },
  { fr: "sel", pt: "sal", type: "n.m." },
  { fr: "servir", pt: "servir", type: "v.", isVerb: true },
  { fr: "soir", pt: "noite (ínicio)", type: "n.m." },
  { fr: "soirée", pt: "noite (durante a noite)", type: "n.f." },
  { fr: "soleil", pt: "sol", type: "n.m." },
  { fr: "sourire", pt: "sorrir, sorriso", type: "v./n.m.", isVerb: true },
  { fr: "s'amuser", pt: "divertir-se", type: "v. pron.", isVerb: true },
  { fr: "se coucher", pt: "deitar-se", type: "v. pron.", isVerb: true },
  { fr: "stylo", pt: "caneta", type: "n.m." },
  { fr: "sucre", pt: "açúcar", type: "n.m." },
  { fr: "sucré, sucrée", pt: "doce, açucarado", type: "adj." },
  { fr: "tableau", pt: "quadro", type: "n.m." },
  { fr: "thé", pt: "chá", type: "n.m." },
  { fr: "trousse", pt: "estojo", type: "n.f." },
  { fr: "utiliser", pt: "usar", type: "v.", isVerb: true },
  { fr: "vacances", pt: "férias", type: "n.f. pl." },
  { fr: "vendre", pt: "vender", type: "v.", isVerb: true },
  { fr: "vers", pt: "em direção a, para", type: "prép." },
  { fr: "village", pt: "vilarejo, aldeia", type: "n.m." },
  { fr: "vite", pt: "rápido, depressa", type: "adv." },
  { fr: "voir", pt: "ver", type: "v.", isVerb: true },
  { fr: "vouloir", pt: "querer", type: "v.", isVerb: true },
  { fr: "vraiment", pt: "realmente, de verdade", type: "adv." }
];

const conjugacoes = {
  "accepter": ["accepte", "acceptes", "accepte", "acceptons", "acceptez", "acceptent"],
  "adorer": ["adore", "adores", "adore", "adorons", "adorez", "adorent"],
  "ajouter": ["ajoute", "ajoutes", "ajoute", "ajoutons", "ajoutez", "ajoutent"],
  "aimer": ["aime", "aimes", "aime", "aimons", "aimez", "aiment"],
  "arriver": ["arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"],
  "attraper": ["attrape", "attrapes", "attrape", "attrapons", "attrapez", "attrapent"],
  "briller": ["brille", "brilles", "brille", "brillons", "brillez", "brillent"],
  "commencer": ["commence", "commences", "commence", "commençons", "commencez", "commencent"],
  "demander": ["demande", "demandes", "demande", "demandons", "demandez", "demandent"],
  "découper": ["découpe", "découpes", "découpe", "découpons", "découpez", "découpent"],
  "goûter": ["goûte", "goûtes", "goûte", "goûtons", "goûtez", "goûtent"],
  "habiter": ["habite", "habites", "habite", "habitons", "habitez", "habitent"],
  "jouer": ["joue", "joues", "joue", "jouons", "jouez", "jouent"],
  "manger": ["mange", "manges", "mange", "mangeons", "mangez", "mangent"],
  "marcher": ["marche", "marches", "marche", "marchons", "marchez", "marchent"],
  "mélanger": ["mélange", "mélanges", "mélange", "mélangeons", "mélangez", "mélangent"],
  "parler": ["parle", "parles", "parle", "parlons", "parlez", "parlent"],
  "préparer": ["prépare", "prépares", "prépare", "préparons", "préparez", "préparent"],
  "regarder": ["regarde", "regardes", "regarde", "regardons", "regardez", "regardent"],
  "ranger": ["range", "ranges", "range", "rangeons", "rangez", "rangent"],
  "utiliser": ["utilise", "utilises", "utilise", "utilisons", "utilisez", "utilisent"],
  "boire": ["bois", "bois", "boit", "buvons", "buvez", "boivent"],
  "courir": ["cours", "cours", "court", "courons", "courez", "courent"],
  "dire": ["dis", "dis", "dit", "disons", "dites", "disent"],
  "écrire": ["écris", "écris", "écrit", "écrivons", "écrivez", "écrivent"],
  "être": ["suis", "es", "est", "sommes", "êtes", "sont"],
  "finir": ["finis", "finis", "finit", "finissons", "finissez", "finissent"],
  "ouvrir": ["ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"],
  "prendre": ["prends", "prends", "prend", "prenons", "prenez", "prennent"],
  "répondre": ["réponds", "réponds", "répond", "répondons", "répondez", "répondent"],
  "sourire": ["souris", "souris", "sourit", "sourions", "souriez", "sourient"],
  "servir": ["sers", "sers", "sert", "servons", "servez", "servent"],
  "vendre": ["vends", "vends", "vend", "vendons", "vendez", "vendent"],
  "voir": ["vois", "vois", "voit", "voyons", "voyez", "voient"],
  "vouloir": ["veux", "veux", "veut", "voulons", "voulez", "veulent"],
  "se laver les mains": ["me lave les mains", "te laves les mains", "se lave les mains", "nous lavons les mains", "vous lavez les mains", "se lavent les mains"],
  "lever la main": ["lève la main", "lèves la main", "lève la main", "levons la main", "levez la main", "lèvent la main"],
  "mettre la table": ["mets la table", "mets la table", "met la table", "mettons la table", "mettez la table", "mettent la table"],
  "s'amuser": ["m'amuse", "t'amuses", "s'amuse", "nous amusons", "vous amusez", "s'amusent"],
  "se coucher": ["me couche", "te couches", "se couche", "nous couchons", "vous couchez", "se couchent"]
};

const conjugacoesPt = {
  "accepter": ["Eu aceito", "Tu aceitas / Você aceita", "Ele/Ela/A gente aceita", "Nós aceitamos", "Vocês aceitam / O senhor aceita / A senhora aceita", "Eles/Elas aceitam"],
  "adorer": ["Eu adoro", "Tu adoras / Você adora", "Ele/Ela/A gente adora", "Nós adoramos", "Vocês adoram / O senhor adora / A senhora adora", "Eles/Elas adoram"],
  "ajouter": ["Eu acrescento", "Tu acrescentas / Você acrescenta", "Ele/Ela/A gente acrescenta", "Nós acrescentamos", "Vocês acrescentam / O senhor acrescenta / A senhora acrescenta", "Eles/Elas acrescentam"],
  "aimer": ["Eu amo/gosto", "Tu amas / Você ama", "Ele/Ela/A gente ama", "Nós amamos", "Vocês amam / O senhor ama / A senhora ama", "Eles/Elas amam"],
  "arriver": ["Eu chego", "Tu chegas / Você chega", "Ele/Ela/A gente chega", "Nós chegamos", "Vocês chegam / O senhor chega / A senhora chega", "Eles/Elas chegam"],
  "attraper": ["Eu pego", "Tu pegas / Você pega", "Ele/Ela/A gente pega", "Nós pegamos", "Vocês pegam / O senhor pega / A senhora pega", "Eles/Elas pegam"],
  "briller": ["Eu brilho", "Tu brilhas / Você brilha", "Ele/Ela/A gente brilha", "Nós brilhamos", "Vocês brilham / O senhor brilha / A senhora brilha", "Eles/Elas brilham"],
  "commencer": ["Eu começo", "Tu começas / Você começa", "Ele/Ela/A gente começa", "Nós começamos", "Vocês começam / O senhor começa / A senhora começa", "Eles/Elas começam"],
  "demander": ["Eu pergunto", "Tu perguntas / Você pergunta", "Ele/Ela/A gente pergunta", "Nós perguntamos", "Vocês perguntam / O senhor pergunta / A senhora pergunta", "Eles/Elas perguntam"],
  "découper": ["Eu recorto", "Tu recortas / Você recorta", "Ele/Ela/A gente recorta", "Nós recortamos", "Vocês recortam / O senhor recorta / A senhora recorta", "Eles/Elas recortam"],
  "goûter": ["Eu provo", "Tu provas / Você prova", "Ele/Ela/A gente prova", "Nós provamos", "Vocês provam / O senhor prova / A senhora prova", "Eles/Elas provam"],
  "habiter": ["Eu moro", "Tu moras / Você mora", "Ele/Ela/A gente mora", "Nós moramos", "Vocês moram / O senhor mora / A senhora mora", "Eles/Elas moram"],
  "jouer": ["Eu jogo", "Tu jogas / Você joga", "Ele/Ela/A gente joga", "Nós jogamos", "Vocês jogam / O senhor joga / A senhora joga", "Eles/Elas jogam"],
  "manger": ["Eu como", "Tu comes / Você come", "Ele/Ela/A gente come", "Nós comemos", "Vocês comem / O senhor come / A senhora come", "Eles/Elas comem"],
  "marcher": ["Eu ando", "Tu andas / Você anda", "Ele/Ela/A gente anda", "Nós andamos", "Vocês andam / O senhor anda / A senhora anda", "Eles/Elas andam"],
  "mélanger": ["Eu misturo", "Tu misturas / Você mistura", "Ele/Ela/A gente mistura", "Nós misturamos", "Vocês misturam / O senhor mistura / A senhora mistura", "Eles/Elas misturam"],
  "parler": ["Eu falo", "Tu falas / Você fala", "Ele/Ela/A gente fala", "Nós falamos", "Vocês falam / O senhor fala / A senhora fala", "Eles/Elas falam"],
  "préparer": ["Eu preparo", "Tu preparas / Você prepara", "Ele/Ela/A gente prepara", "Nós preparamos", "Vocês preparam / O senhor prepara / A senhora prepara", "Eles/Elas preparam"],
  "regarder": ["Eu assisto", "Tu assistes / Você assiste", "Ele/Ela/A gente assiste", "Nós assistimos", "Vocês assistem / O senhor assiste / A senhora assiste", "Eles/Elas assistem"],
  "ranger": ["Eu arrumo", "Tu arrumas / Você arruma", "Ele/Ela/A gente arruma", "Nós arrumamos", "Vocês arrumam / O senhor arruma / A senhora arruma", "Eles/Elas arrumam"],
  "utiliser": ["Eu uso", "Tu usas / Você usa", "Ele/Ela/A gente usa", "Nós usamos", "Vocês usam / O senhor usa / A senhora usa", "Eles/Elas usam"],
  "boire": ["Eu bebo", "Tu bebes / Você bebe", "Ele/Ela/A gente bebe", "Nós bebemos", "Vocês bebem / O senhor bebe / A senhora bebe", "Eles/Elas bebem"],
  "courir": ["Eu corro", "Tu corres / Você corre", "Ele/Ela/A gente corre", "Nós corremos", "Vocês correm / O senhor corre / A senhora corre", "Eles/Elas correm"],
  "dire": ["Eu digo", "Tu dizes / Você diz", "Ele/Ela/A gente diz", "Nós dizemos", "Vocês dizem / O senhor diz / A senhora diz", "Eles/Elas dizem"],
  "écrire": ["Eu escrevo", "Tu escreves / Você escreve", "Ele/Ela/A gente escreve", "Nós escrevemos", "Vocês escrevem / O senhor escreve / A senhora escreve", "Eles/Elas escrevem"],
  "être": ["Eu sou/estou", "Tu és/estás / Você é/está", "Ele/Ela/A gente é/está", "Nós somos/estamos", "Vocês são/estão / O senhor é/está / A senhora é/está", "Eles/Elas são/estão"],
  "finir": ["Eu termino", "Tu terminas / Você termina", "Ele/Ela/A gente termina", "Nós terminamos", "Vocês terminam / O senhor termina / A senhora termina", "Eles/Elas terminam"],
  "ouvrir": ["Eu abro", "Tu abres / Você abre", "Ele/Ela/A gente abre", "Nós abrimos", "Vocês abrem / O senhor abre / A senhora abre", "Eles/Elas abrem"],
  "prendre": ["Eu pego/tomo", "Tu pegas/tomas / Você pega/toma", "Ele/Ela/A gente pega/toma", "Nós pegamos/tomamos", "Vocês pegam/tomam / O senhor pega/toma / A senhora pega/toma", "Eles/Elas pegam/tomam"],
  "répondre": ["Eu respondo", "Tu respondes / Você responde", "Ele/Ela/A gente responde", "Nós respondemos", "Vocês respondem / O senhor responde / A senhora responde", "Eles/Elas respondem"],
  "sourire": ["Eu sorrio", "Tu sorris / Você sorri", "Ele/Ela/A gente sorri", "Nós sorrimos", "Vocês sorriem / O senhor sorri / A senhora sorri", "Eles/Elas sorriem"],
  "servir": ["Eu sirvo", "Tu serves / Você serve", "Ele/Ela/A gente serve", "Nós servimos", "Vocês servem / O senhor serve / A senhora serve", "Eles/Elas servem"],
  "vendre": ["Eu vendo", "Tu vendes / Você vende", "Ele/Ela/A gente vende", "Nós vendemos", "Vocês vendem / O senhor vende / A senhora vende", "Eles/Elas vendem"],
  "voir": ["Eu vejo", "Tu vês / Você vê", "Ele/Ela/A gente vê", "Nós vemos", "Vocês veem / O senhor vê / A senhora vê", "Eles/Elas veem"],
  "vouloir": ["Eu quero", "Tu queres / Você quer", "Ele/Ela/A gente quer", "Nós queremos", "Vocês querem / O senhor quer / A senhora quer", "Eles/Elas querem"],
  "se laver les mains": ["Eu lavo as mãos", "Tu lavas as mãos / Você lava as mãos", "Ele/Ela/A gente lava as mãos", "Nós lavamos as mãos", "Vocês lavam as mãos / O senhor lava as mãos / A senhora lava as mãos", "Eles/Elas lavam as mãos"],
  "lever la main": ["Eu levanto a mão", "Tu levantas a mão / Você levanta a mão", "Ele/Ela/A gente levanta a mão", "Nós levantamos a mão", "Vocês levantam a mão / O senhor levanta a mão / A senhora levanta a mão", "Eles/Elas levantam a mão"],
  "mettre la table": ["Eu ponho a mesa", "Tu pões a mesa / Você põe a mesa", "Ele/Ela/A gente põe a mesa", "Nós pomos a mesa", "Vocês põem a mesa / O senhor põe a mesa / A senhora põe a mesa", "Eles/Elas põem a mesa"],
  "s'amuser": ["Eu me divirto", "Tu te divertes / Você se diverte", "Ele/Ela/A gente se diverte", "Nós nos divertimos", "Vocês se divertem / O senhor se diverte / A senhora se diverte", "Eles/Elas se divertem"],
  "se coucher": ["Eu me deito", "Tu te deitas / Você se deita", "Ele/Ela/A gente se deita", "Nós nos deitamos", "Vocês se deitam / O senhor se deita / A senhora se deita", "Eles/Elas se deitam"]
};

// Ordena o dicionário em ordem alfabética no momento do carregamento
dicionario.sort((a, b) => a.fr.localeCompare(b.fr));
